spring:
  datasource:
    url: jdbc:mysql://localhost:3306/intellekta
    username: intellekta
    password: intellekta
    driverClassName: com.mysql.jdbc.Driver
    initialization-mode: always
    continue-on-error: true
  jpa:
    database: mysql
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true